### ISSUE TITLE
Resource Page is not responsive

### ISSUE THREAD

**Issue by Adushaiq** [Aestheticsuraj234/codersyug#1]
https://codersyug.vercel.app/resources

This page is not responsive, the slider containing different technologies which can be used to search the resources is overflowing.
Also the close button is disappearing from the nav bar after clicking on resources, which in turn doesnt let the user close the nav bar in mobile devices.

https://github.com/Aestheticsuraj234/codersyug/assets/91279802/650a4c27-a87f-46f9-a7a4-53776490e7e7

![Codersyug-A-community-for-developers-by-developers](https://github.com/Aestheticsuraj234/codersyug/assets/91279802/995afc53-6ebb-4747-9d7a-6b603ef4b8de)

**Comment by Aestheticsuraj234** [comment]
Hello  @Adushaiq  we will going to fix it soon as well due to overflowing of filters category in resources our navbar is stretch towards all the width due to which out cross button is disappear so thanks for raising the issue **Thank you**
